### ISSUE TITLE
ac-prez todos

### ISSUE THREAD

**Issue by houshuang** [chili-epfl/FROG#1159]
I got this error sometimes when paging rapidly through.
<img width="1064" alt="screen shot 2018-05-18 at 20 38 00" src="https://user-images.githubusercontent.com/61575/40252393-80fa0a54-5adc-11e8-8f2f-0d495e8286eb.png">

Not sure if this is the same as before with fonts, but page 31 of the PDF I sent you a link to still crashes. 

We should both fix this individual crash, but also make sure that a crashing slide can never crash the whole activity (with [React error component](https://reactjs.org/blog/2017/07/26/error-handling-in-react-16.html))

- The student view refreshes even if the student is locked on a page (individual navigation), whenever the teacher advances (here we could use shouldComponentUpdate)

- It should be possible to navigate using arrow keys. You can use Mousetrap (see GraphEditor/index). Also add buttons for first and last page. And for student, a button to catch up to teacher. 

- I still think it's better to have the four colors as separate boxes, much quicker if you quickly want to highlight some stuff in different colors. And there is no point in many color. Probably make default width 5 or something - so it's visible

- Should the area (box) have the same color/thickness as the drawing tool?

- Enable deleting annotation with backspace button? 

- Hide redo button when user has not pressed undo (most common case)? 

- Bonus feature: Don't know if it's easy, but it would be nice with a button that would switch to a scratchpad, basically a toggle, where teacher could still annotate - maybe this would be a blank PDF? Let's say someone asks a question, and the teacher quickly wants to illustrate something, and then switch back to the slides?

- Option to force student to follow teacher

- Option to not let student advance beyond teacher

- Option to let everyone turn pages and annotate

**Comment by dinomujki** [comment]
Updates (new branch 'prez'):
 - Biggest update was a major change in how I store annotations, both in the db and in localStorage. Main shift is that annotations are divided per page now. This was not only needed to properly implement UNDO/REDO, but for optimization as well.
 - Student and Teacher page rendering was further optimized, I cannot break it in any manner when testing even if you go way too fast for the browser (in other words, should be fail-safe now in terms of rendering, have not found the time to focus on the invalid characters as well)
 - Added page navigation using arrow keys. Added First and Last page as well, will likely switch this to a 'Go To' input later. Added also the bool to force the student to simply follow the teacher.
 - I don't think it's possible to change the box area display (in terms of color or width), will look more into it.
- UNDO and REDO both now properly display when they are invalid (disabled)
- Separated the 'config' file, made it clean and improved the booleans
- TESTING: Rendering of the page should now be extremely hard to break (I cannot find a way to do it expect for the Asian chars), while it will stall at times, it should always eventually render (usually within a sec because my timeouts are 500ms now).

**Comment by houshuang** [comment]
- If you select some text, choose Strikethrough, and leave the text selected while you click undo, it will automatically re-apply Strikethrough. I guess undo should first cancel text selection or something like that.
- The scratchpad does not seem to be shared with students? The teacher gets it and can annotate, but the student a) doesn't switch automatically, b) if he/she switches, he/she sees nothing
- If student cannot go further than teacher, the next page button shouldn't be shown (unless student is behind)
- Currently when the student cannot go beyond the teacher, it looks at the last page the teacher every viewed, even if the teacher goes back. People often flip through their entire presentation at the beginning to check that everything works, so we should instead look at the current teacher slide, and not go beyond that.
- It doesn't work with two windows in preview (not the end of the world, but I thought it used to work)
