### ISSUE TITLE
ac-ranking doesn't work in read-only mode

### ISSUE THREAD

**Issue by houshuang** [chili-epfl/FROG#1162]
If ac-ranking is displayed in read-only mode, for example because the teacher chose "only teacher can edit" in a p3 activity, ac-ranking crashes, because of these lines in src/ActivityRunner/index.js:

```js
  if (!answers[userInfo.id]) {
    dataFn.objInsert({}, ['answers', userInfo.id]);
    dataFn.objInsert(userInfo.name, ['group', userInfo.id]);
  }
```

It tries to set userInfo, which results in a re-render, when it tries to set it again, etc, ending in a crash.

Not sure what is a good way of solving this. The idea was that activities should be able to be put in read-only mode without actually changing the activity code (if props.readonly then...). Anyway the way we're dealing with student data here is a bit hacky, there might be a better general approach.

**Comment by lfaucon** [comment]
I think it is bad practice to do things that will trigger a re-render from the render function in general.

I'd say adding a `readOnly` props would make sense, because our activities do not make sense for now in read only mode. For example on this interface the student will be want to click the buttons or submit, but that would do nothing. I prefer that the interfaces are slightly different with some conditions in the code, than that.

![screen shot 2018-06-06 at 10 25 07](https://user-images.githubusercontent.com/8818081/41015288-ef860c20-6973-11e8-8b3d-f0bd27d971ae.png)

**Comment by houshuang** [comment]
Agree that adding props is a good idea, but we should also write activities robust enough to not rely on state changing.
