### ISSUE TITLE
Wiki storing code in ShareDB

### ISSUE THREAD

**Issue by houshuang** [chili-epfl/FROG#1666]
@dinomujki , I'm assuming this is not intended? (From a wiki link to a non-existent page)

<img width="693" alt="Screenshot 2019-04-29 at 09 34 56" src="https://user-images.githubusercontent.com/61575/56882061-b7881980-6a62-11e9-87cc-901e60557b65.png">

**Comment by dinomujki** [comment]
Okay, I tracked down why I had this code in the data object in the first place and realized that this was a workaround for the entire separation of frog-utils from the frog app and the difficulty of performing shareDB ops on the wiki collection from within frog-utils. I've been looking at it for quite some time now and trying other stuff but passing in the createPage function through the wikiContext still seems to be the only direct viable solution (however I don't know enough about the FROG structure so there could be another more elegant solution for creating links to non-existing pages when you don't first know their ID).

But the code will not be stored in the shareDB, this was easily fixed by:
https://github.com/chili-epfl/FROG/commit/0ef0ff5c764e625122d0161ea682812ca14f8e79

**Comment by houshuang** [comment]
Maybe use global
