### ISSUE TITLE
Adding NPM API to FROG 

### ISSUE THREAD

**Issue by sintaz1992** [chili-epfl/FROG#1908]
Hi,
For connecting Thymio robots to FROG, I need to add an API named "@mobsya/thymio-api" and use it in the dashboard. We tried to add this to the packages inside FROG but we couldn't. 
So I have two questions: first how to add this to the package should work and if this API, itself, has some dependencies should I add all the dependencies too?

**Comment by houshuang** [comment]
Hi. Can you explain how you tried to add it? Note that because of our slightly weird setup, you need to do something special, this is in the main README.md:
  - to add dependencies or do other yarn actions, first do `npm start unlink`, then do your actions, and then `npm start link` to
Also, once you add the main dependency, all recursive dependencies will be added automatically.

**Comment by sintaz1992** [comment]
Thank you Stian, 
it seems the problem was about the API itself. Instead of adding the package to FROG, I had to send the data from API to FROG by websocket, the way that we send data from cellulo, and it works well.
