### ISSUE TITLE
[Tests] Add more tests 

### ISSUE THREAD

**Issue by lfaucon** [chili-epfl/FROG#22]
Trivial testing has been implemented using Circle-CI (#7).
See the good practice for implementing more tests here: https://www.meteor.com/tutorials/react/testing

**Comment by lfaucon** [comment]
Tests have been fixed (#29) by #30

**Comment by houshuang** [comment]
Just adding some thoughts about how we could implement this. 

# Better documentation
It's easy to loose track of what different activities/operators are supposed to be doing, when you are working on different parts of FROG, and need to review a pull-request (and the API might have changed etc). This will become even more important once other people are using the system of course... For now, how about adding a documentation to the metadata of operators/activities, which should specify quickly the intended meaning/functionality of the operator, and also the API... 

Eventually we can think of improving the description which is shown to end-users (screenshots of activities for example), but also the specification of the API (making it machine-readable and enabling the graph editor to keep track of which inputs match which outputs, etc).

Tests will also function as a form of documentation for developers, see below.

# Operators
Currently all operators are state-less, single-pass and don't access external resources (we currently don't have "Get stockprices operator" etc), or interact with the user. This could change. But for now, simple unit testing (data in -> expected data out) should be quite easy to implement. This should also include cases with missing data, etc. 

# Activities
We could use a unit test to test that a component renders according to certain data. Facebook's jest has a interesting "snapshot" functionality - the first time you run a test with a specified input, it stores the output, and if you rerun the test, it will compare the output to make sure it hasn't changed... Thus we could provide different forms of example input for the main activity, and also the dashboard etc. (Ie. different forms of config, but also different props by mocking the reactive data structures).

We could also do a form of integration testing. I'm thinking of adding an activityRunner to the main FROG tool which exists independent of the graph, which would make it easy to just run a single activity in isolation, given a specific set of config and inputdata... this would enable for example setting up a config, and running two front-end instances through nightmare.js, and simulating users interacting etc, without worrying about the rest of FROG.

# The engine
Again, individual components could be "unit-tested" using Jest snapshots (for example, the graph editor should look the same given the same graph). We could also write a few integration scripts that go through a fairly complex workload (perhaps recording the scripts using the nightmare browser plugin), to test that all components are working together...

---

We have to look at what to prioritize here, given that things will still be changing pretty rapidly. But we should begin to document things, as interfaces begin to fall into place... When it comes to operators and activities, I think we still have some major questions about data formats, social/product operators, and logging - but once we can figure that out, we should aim to begin to stabilize the API interface... And eventually we want to move to version numbers that actually mean something - having an activity that depends on a specific version of FROG, etc.

Because eventually, we will need to support FROG in "action"... whether it's a version running for Thanasis' class, or it's a version used in Pierre's MOOC, or the version used in Valerie's classroom... We need something fairly stable and well-tested, where can still backport bug fixes and quick enhancements, while at the same time working on major new issues etc... And it would be nice to have someone be able to focus on developing an awesome activity, without worrying about FROG changing too much "under their feet"...

(And to be able to upgrade to a new version of Meteor or React, without worrying about our code failing in an edge case)

**Comment by houshuang** [comment]
We have made significant progress on this, but much remains to be done - especially testing activities, and dataflows/script execution. Closing this, feel free to reopen more specific issues.
