### ISSUE TITLE
Designing user management interface, extensible log-in flows

### ISSUE THREAD

**Issue by aperritano** [chili-epfl/FROG#245]
Not an issue, but an enhancement request to the wiki docs. 

FROG has a reference UI in which the login is at the upper left hand side with a drop down menu to enter in credentials. If we have a scenario where one would want to have a front facing login box where a user logs in, the system determines if they are a student or teacher or etc.., the system displays either students list of brainstorms or the teachers running brainstorms and list of teacher views for those instances. When developing this interaction flow does FROG have SYSTEM services that can be leveraged? For instance, a dev could make their login UI, when the user enters their credentials, use a login service to determine what they should see and return that data to be displayed. Whether it is a teacher or student, etc... How would one go about this? What are the endpoints? Is this were the socialStructure and ActivityStructures come in?

**Comment by houshuang** [comment]
Basically, right now all the explicit extension points in the system are focused around activities and operators - making it possible to develop new kinds of graphs (collaborative learning scenarios). We have also focused the tiny documentation we have on these concepts (including socialStructure etc). In general, we've given extremely little thought to login/user management, general UI etc, not because they are not important, but because we wanted to focus on developing the core functionality (proof of concept - is it even possible), and also because the ideal login flow will differ for different situations etc.

Basically, the way it works currently (which can be changed), is that we're leveraging Meteor's built-in login functionality, which has a very simple system of users, logged in state, persisting log-ins etc. Currently there is no concept of permissions in the system (anyone can see/do anything), which is obviously only temporary.

A teacher can launch a new session based on a graph, and students can either manually join, or the teacher can use Join all online students (mainly implemented for testing). Currently students can only join after a session has been initiated, but before it has begun running activities - we should probably change this, but need to make sure that all the operators are robust to changing student populations (what to do if a student joins after students have been grouped, etc).

In terms of mechanics, this works through querying/subscribing to Mongo collections using Meteor, the users collection, and the sessions collection. 

To my mind there are two components needed: a user management interface (for admins to add teachers/researchers, for teachers to add students (manually, by uploading CSV file etc), to easily add students to different runs etc. The second is the actual login workflow - whether a student enters their name, and sees a list of sessions, or they go a unique URL per session, and type in their name etc. This depends a lot on how much security is needed (passwords etc), and how closely data needs to be normalized (is it OK that students type in their own name, or do we need to be able to connect accounts to accounts in other systems for grading etc).

We will also probably be working on some external integrations this fall, for example log-in through Moodle.

I think it would make sense to have a single user management system, however it would be great to have some kind of abstraction around the actual log-in flow, because I could imagine having a bunch of different systems (Moodle single sign on, QR codes, username/password, etc). 

-- 

A more philosophical discussion is whether we see FROG as primarily a system running on many different servers, with each instance typically serving a single teacher/run/experiment (ie. each server would have maximum a few classes, a handfull of teachers, tens of runs etc), or whether we see it more towards centralized installations at school level (or us offering a semi-open instance for anyone interested), where you would have hundreds, thousands of teachers, runs, sessions etc. I think for now (until we get external funding and full-time developers ec), we're focusing on the first scenario - making it extremely easy for anyone to spin up their own instance. We might host a semi-public instance at EPFL but it will be limited to our friends, for trying out, etc.

--

Finally, right now the security of the system is wide-open. This means that a semi-skilled student can open console, and mess with everyone's data. There are mechanisms in Meteor for controlling access, by making subscriptions to different subsets of collections explicit - to help in prototyping, we use auto-publish, which let's everyone see everything. 

Lot's of work to be done :)

Including @lfaucon in discussion.
