### ISSUE TITLE
Use Case - How to disable the mosaic frame and top toolbar for StudentView? [priority]

### ISSUE THREAD

**Issue by aperritano** [chili-epfl/FROG#302]
<img width="863" alt="screen shot 2017-07-02 at 7 58 41 pm" src="https://user-images.githubusercontent.com/219031/27774913-05df08d2-5f61-11e7-988c-11400a93e0a3.png">

I'm building this layout that starts with a top bar. The top bar and mosaic window is taking up a lot of unnecessary space. How can we mitigate this situation most optimally?

Just riffing...
One suggestion is to have a boolean flag for activities called 'fullscreen', removes the topbar and window. Passes the proper data to activity for building its own login, title elements etc... 

Another could be to have submodule structure similar activities and operators for layouts; e.g., lo-tabs, lo-fullscreen, lo-titlebar-tabs, lo-split,  etc... and with a dropdown menu (similar to the activities) in the graph editor in which one can choose what layout to use when activities are rendered during the timeline. 

I not sure how optimally these are, the activityview ui in frog>imports looks quite involved.

**Comment by houshuang** [comment]
So two things
- the navigation bar for students: this was never supposed to be there, and it's only because we haven't gotten that far
- the chrome around activities if you only have one activity: a single activity could be special-cased

I have a branch (studentview) where I experimented with both of these. I decided to remove the login button for now and just use the URL login, so that localhost:3000/#/teacher/[view] logs in as teacher, with the navigation bar, and optionally selects the view (graph/teacher/admin etc). Any other user (like localhost:3000/#/ole) logs in as that student, in the studentview, with no navigation bar and no possibility of "escaping".

(Thus currently the only teacher is the user called 'teacher'. Easy to replace this check with a check of user.teacher = true or something like that once we have more sophisticated user management).

In the branch referred to above, the first part works well, but I'm getting some weird bugs in the second part, in student/Runner.jsx. I don't have time to look at it right now, but anyone else feel free to pick up :) 

The third issue is more about a specific layout etc. I have some ideas about this, but this probably won't happen in the immediate future. Could you tell us more about the specific script you are thinking of designing, are you planning multiple activities present at once, what kind of layout would you need, etc?

**Comment by houshuang** [comment]
See #304
