### ISSUE TITLE
Activity Runner vs Component in activity index.js

### ISSUE THREAD

**Issue by aperritano** [chili-epfl/FROG#314]
Looking at ac-text and ac-ck-board, the index.js has two different ways to initialize the components. 

**ac-text:**
```
export const ActivityRunner = ({ activityData }: ActivityRunnerT) =>
  <div>
    <h1>{activityData.config ? activityData.config.title : 'NO TITLE'}</h1>
    <p>{activityData.config ? activityData.config.text : 'NO TEXT'}</p>
  </div>;
```

```
export default ({
  id: 'ac-ck-student',
  meta,
  config,
  ActivityRunner,
  Dashboard: null,
  dataStructure,
  mergeFunction
}: ActivityPackageT);
```

**ac-ck-board:**
```
export default ({
  | id: 'ac-ck-board',
  | meta,
  | config,
  | ActivityRunner: Board,
  | Dashboard: null,
  | dataStructure,
  | mergeFunction
  | }: ActivityPackageT);
```

The activity runner takes a component 'Board' from file board.js in the ck-board's case. But the actual class in that file is called 'Cluster'. Why pass board to the activity runner, why not make a ActivityRunner const  in the former case and add the Cluster tag? How is Board -> Cluster receiving all of the config, activitydata etc? When not to use the ActivityRunner const as a start point? 

**React Naming conventions and file extensions vs FROG naming conventions**
The convention is to capitialize and use the .jsx extension:
https://github.com/airbnb/javascript/tree/master/react#naming

within FROG many files are lower cased with .js extension, but some are capitalized; e.g. Chat.jsx in ac-chat.
when to use what?

**Comment by houshuang** [comment]
Hi Tony,

not all of our code follows best practices (yet), especially some of our activities which were sometimes hacked together to try something, and whose code isn't touched frequently (as opposed to core engine stuff). 

The reason the Cluster/Board stuff works is that Cluster is exported as default, and the import is 

```
import Board from './board';
```

not 

```
import { Board } from './board'
```

which would have failed. 

The final exported object needs a React Component in the ActivityRunner slot, whether that component is defined in the index.js file, or imported from another file, makes no difference.

Note that in ES6, `{a}` is syntactic sugar for `{a: a}`, so in the first example, we are actually doing `{ActivityRunner: ActivityRunner}`. What the component is actually called in index.js is arbitrary, we could have done

```
const ActivitySomething = ...
```

and

```
export default { ActivityRunner: ActivitySomething, config ... }
```

About naming, we have not been 100% consistent. I'm not sure myself. I'm leaning towards not using JSX, because all of our JS files are interpreted as JSX anyway, and it's stupid to have to change extension if you suddenly include a bit of JSX in a file that didn't have it before. React components have to be capital case, but a file that exports multiple components (maybe bad practice, but it happens)? ...

**Comment by aperritano** [comment]
OK, no worries on the different styles of naming, etc.. 

So going forward, what do you want the conventions to be? I'm OK whatever, as long its consistent. 

The Airbnd standards seem to widely adopted and can be configured checked with eslint.
