### ISSUE TITLE
Moving activities between interaction levels on the graph editor.

### ISSUE THREAD

**Issue by aperritano** [chili-epfl/FROG#323]
Allow the user to change the interaction level (individual, group, class) of the activity without having to delete it and create a new one, especially after configuring it.

**Comment by houshuang** [comment]
This is a bit of a "theoretical problem" for us, since the theory says that all activities are hard-locked to a specific plane (ie. individual video watching and group video watching are two different activity types, not the same activity on two different planes). In the actual implementation we landed on, however, it is much more flexible. I wouldn't expect any movement on this very soon, however we are in general interested in more flexibility in the editing environment, in terms of copying and pasting, replicating activities etc, and we can revisit this in the future.
