### ISSUE TITLE
Image/video upload in activities

### ISSUE THREAD

**Issue by aperritano** [chili-epfl/FROG#324]
Has there been any thought to the use of binary data such as images and video upload in during activities? For instance,  in activity, a student supporting their note with image evidence. In Toronto, there was a service that served up static image urls on upload. Thoughts about that in FROG?

**Comment by houshuang** [comment]
Absolutely, we're in the process of building that now, because we will also need it for this fall. The idea is a component, probably as part of react-jsonschema-form, which gives a file-uploading button. Upon upload, the file is placed on the server, and a URL is added to the form field (to be stored in the normal database, forwarded to operators etc). I guess there might be other ways of uploading (Drag+drop, open webcam and take photo etc) which we should also investigate. There are also some security issues (how do we keep track of who is supposed to have access to a file, given that a graph can be complex) - however with a long random URL, and limiting access to logged in users, I'm not overly concerned.
