### ISSUE TITLE
Full Lodash in Bundle?

### ISSUE THREAD

**Issue by curran** [chili-epfl/FROG#638]
https://github.com/chili-epfl/FROG/blob/5529d427c03422a7842b654ca9f62e0d1dd8cc47/frog-utils/src/generateReactiveFn.js#L4

You may want to do an experiment and change this

```js
import { get } from 'lodash';
```

to this

```js
import get from 'lodash/get';
```

and compare the bundle sizes. In my experience, the latter reduces the bundle size dramatically. With the first option, all of Lodash gets included into the bundle (unless Babel recently changed to optimize this).

**Comment by houshuang** [comment]
Hi, thanks a lot for this comment. Frog-utils is only used by FROG, which imports a bunch of different packages, many of which use different lodash functionality. However, we are moving towards doing more code-splitting/conditional imports, and in that case, being more specific about which specific code we require might make a difference!

Also looking forward to tooling better supporting this, so that you can just import the pieces you need and not worry about the rest. I guess we're getting there slowly.
