### ISSUE TITLE
Add Example Graphs to Preview

### ISSUE THREAD

**Issue by aperritano** [chili-epfl/FROG#721]
The preview functionality is great. Especially the options for previewing with users. What if a user wants to replicate that structure to start? It would be nice to have something like "start with this graph" or "add to existing graph" to the teacher view. Even just simply to show the underlying graph.

**Comment by houshuang** [comment]
I don't entirely understand your question. There is no graph - all you are seeing is a single activity, optionally with multiple users logged in.

Are you saying that you like the example data, and you'd like an activity configured like the example data to be added to your graph?

Or are you saying that you would like to preview an entire graph that you have designed in the same fashion (with multiple students open at the same time in one window etc)? That would be theoretically possible, but would require a lot of work, and it's also a bit limiting since you might often have more than one activity open at the same time, which would become very cramped if you had multiple students on a single screen.

**Comment by aperritano** [comment]
"Are you saying that you like the example data, and you'd like an activity configured like the example data to be added to your graph?”

Right there is no graph. The first question a user will ask themselves: “How do I set the activity up like this?”. For now it could be a screen shot or a bunch of steps in how to create the graph like that. Bonus, if there was a button that said “Create new graph from example” or something. Examples as starter templates.

I could imagine different CK examples. One could quick start making a graph via that.

**Comment by houshuang** [comment]
Again, the activity preview is not a graph, it's a single activity. In fact, the default entry point should be by clicking on the graph to create an activity, and then seeing previews of activity types. Once you choose an activity type, you can configure it, and preview how it will look with your config... Given that the config is usually just a few lines, I don't see any advantage to letting people create an activity from the example data. In the future, we might have templates for common sequences of activities - jigsaw where you can fill in the question etc. 

Note that the separate preview functionality is mainly for activity developers, because it provides a stable URL that survives reloads (when developing an activity etc).
