### ISSUE TITLE
Choosing a graph library for FROG

### ISSUE THREAD

**Issue by houshuang** [chili-epfl/FROG#730]
We use graphs a lot for dashboards etc in FROG. I'm not happy with how the current graphs look/respond. There are a lot of very nice options. I also feel that it would be useful to standardize on a single one, at least for core FROG stuff (and recommend activities to use the same) to avoid pulling in too many heavy dependencies. 

There is a nice overview of various React-focused options [here](https://mux.com/blog/so-we-redid-our-charts-part-ii-graphing-react-ing-and-maybe-a-little-crying/). They end up recommending either [Victory](https://formidable.com/open-source/victory/) or [Recharts](http://recharts.org/#/en-US/).

I have also been looking at [Plotly](https://plot.ly/javascript/), which is not written for React, but has React bindings. It also has a Python package, which might be relevant for integration with external operators (but probably not, they would just emit a list of numbers and we would graph them using the front-end anyway).

Not sure how to proceed - all three (Recharts, Victory, Plotly) look very nice - used by big companies, lot's of graph types, configurable, nice interaction (zooming, facetting etc)... Do you know of any other candidates we should consider, or how should we choose?

**Comment by aperritano** [comment]
What do you think are the most common graph types you will be using? How often do you think you will need a custom visualization; non-standard chart? 

Victory is D3-based which is a major plus. Plotly too. I would go with Victory for now. I'm a bit bias for D3 because I know what it can do on scale. For basic graphs to custom visualizations. 

https://medium.com/@Elijah_Meeks/interactive-applications-with-react-d3-f76f7b3ebc71

**Comment by prastut** [comment]
Cross posting from email conversations for better visibility and documentation: 


### Visual Components: 
* How Google does it: 
  * inside Google Map -> it renders information according to the zoom level you are in. More dense info when you zoom more. 
  * Google Analytics also recomputes based on what filtering you choose. 
* How any currency site does it with price fluctuation charts: 
  * https://www.coindesk.com/price/ - They divide data by the period you want to see in: "1 hour, 12 hours 1 day ... All" so when you press on all it reloads the chart with fine data points.
  * One more eg: https://coinmarketcap.com/currencies/bitcoin/ 

Note: These are just examples where I have noticed that charts only have zoom component (not panning/scrubbing since that requires constant data fetching. Even if they allow, the graph takes time to reload)

### Tech
I am not very sure but React's virtual dom would increase performance in such cases. 
* Chart config (on top of my mind):
  * Adding node -> shouldn't recompute the whole graph, just add the node to the DOM. 
  * Adding node and affecting previous nodes -> in this you would have to recompute the whole graph. 
  * Interactivity with the nodes ( tooltips, legends, zooming, panning etc)

#### Performance (SVG vs Canvas): 
The libraries which create SVG elements will always be inferior to libraries that create Canvas elements when you have a large dataset. Reason: SVG is not hardware accelerated there could be performance issues if an application uses too many SVG objects. Many browsers have the feature to use GPU to perform 2d canvas rendering instead of using software rendering. 

* Some examples where performance is being compared: 
   * SVG vs Canvas: https://codepen.io/chris-creditdesign/details/BIADJ
   * Try adding different amount of circles: http://tommykrueger.com/projects/d3tests/performance-test.php
   * http://nivo.rocks/#/scatterplot/canvas

Victory and Recharts both make SVG elements under the hood. Though Victory specifically has a guide on performance on how to use it for large datasets, [demo](https://formidable.com/open-source/victory/guides/zoom-large-data/#demo) . They also suggest [Crossfilter](http://square.github.io/crossfilter/) for filtering/sampling. Canvas Based Libraries: [Canvas.Js](https://canvasjs.com/docs/charts/intro/high-performance-javascript-charts/) (it renders 100,000 points without sweating)  

Ultimately it boils down to how much data is being visualized on the frontend and what level of interactivity we want, based on that we can choose how to implement it in tech. 


### General Thoughts 
With GoogleVis, problem is that it’s JQuery or something like that wrapped as a React component (basically just taking care of calling the right methods when props change etc), which means it doesn’t take advantage of React’s VDOM etc.

We have concerns, which relate to modularity - it should be as easy as possible to build new dashboards, without changing the entire core or inventing a new data streaming format. There is the live streaming data problem, and also distributing processing between front-end and back-end (which includes not only the actual data given to the graph - and here we can be more intelligent and not give it 4000 data points to plot if a sampling of 10% of data points would look visually exactly the same - but also whether that calculation happens in the browser or the backend etc)… 

And then there are also discussions about whether we can come up with some nice visualization abstractions, and build very nice interfaces that can show many different types of data - this would also let us ideally filter/zoom, show outliers vs central tendencies etc. But again, having this possibility would probably require more detailed underlying data - and what is the best “aggregated format”, and where does aggregation happen etc. (And we haven’t even begun adding ML algorithms to the mix! Imagine if we want to show not some single metric, but an evolution of sentiment analysis scores per student group, over time.

**Comment by houshuang** [comment]
@prastut @lfaucon Seems like everyone is happy with Victory so far?
