### ISSUE TITLE
Some suggestions on ac-autocode

### ISSUE THREAD

**Issue by houshuang** [chili-epfl/FROG#750]
- Rename debug to "run", or "try"
- The Javascript has access to all the global environment - console.log goes to the browser log (not the output window), and if I do window.location.href = "google.com", the whole window changes location etc. Not really a security issue since it only runs locally in the browser, but it would be sad if the user managed to crash all of FROG because of some error in their code. Not sure if it's possible to sandbox it better - avoid any global effects.
- show some reload icon or some indication on the buttons that you can rerun them after you have made them red/green

**Comment by Keylas** [comment]
Debug is indeed unclear about it being "debug mode" and not "help me debug".

I'm a bit confused by the javascript global environment because I believe it was not the case at some point.
A solution I had was to use a Proxy object for the environment but that would need `with Proxy(object)` and `with` is not allowed in strict mode.
I think using a web worker may solve the issue (and I understood React uses them so at first I conceived it was handling the problem). Sorry it turned out not to work properly.
