### ISSUE TITLE
ac-autocode dashboard fails with no tests

### ISSUE THREAD

**Issue by houshuang** [chili-epfl/FROG#767]
It is possible to configure autocode to run without any tests (this is the default), and the activity works fine for students, but when a teacher tries to see the dashboard, it fails saying "Cannot read property tests of undefined"...

It's OK if there is no useful info to report, but make sure it does not fail given valid config.

**Comment by Keylas** [comment]
I believe the issue happens when nothing is filled and the `config` is then `undefined ` ? (seems to work if I do not put tests but fill in a title).
I'm not sure an undefined config can be caught by `validateConfig` since at `frog/imports/api/validateConfig` l.84, `datafns && obj ? compact(datafns.map(fn => runFn(id, fn, obj))) : [];` seems not to apply if the config `obj` is undefined.
I guess having the title be required fix the issue since the config would not be undefined anymore then ? (see #770)
