### ISSUE TITLE
Versioning of graphs, activity types

### ISSUE THREAD

**Issue by houshuang** [chili-epfl/FROG#775]
Currently, if a new version of an activity type is installed, which has a different config data configuration, it breaks an old graph. As we start building up an activity library, this becomes untenable. 

The way H5P does this (also the way Erlang handles code upgrades in place), is to 
a) have a version on all data
b) when you release new code which requires changes, include an upgrade function going from for example 1.0 to 1.1, a function that takes a 1.0 config data obj, and upgrades it to 1.1
c) the engine would use this to automatically upgrade old config data
d) if the engine encounters 1.0 data and is at 1.2, it would run both the 1.0->1.1 function and then the 1.1->1.2 function

We should
a) have a version in the metadata of FROG, and of all ac/op types
b) store this version number as part of a graph export or as the config data of activities
c) enable these upgrade functions

We also enable update functions at the graph level - these could either completely change the export format of a graph, or rename activities (imagine if we renamed ac-image to ac-gallery, this would break all the UNIL graphs)

Note that these versions etc are independent of NPM versions etc - they refer to the version of the config data format, and not of code compatibility. (In the future, once activity packages and FROG packages are released independently, you could have a new version of the video activity, which was only compatible with a certain version of the FROG core - but the config format would not change, and the config version would thus remain the same).

**Comment by houshuang** [comment]
Specifying a bit:

First, we need the export tool (luckily we're using the same code for file downloads as for sending to the "cloud", right?) to add versions. These should be 1 for the graph as a whole, and 1 for all activities and ops by default. (Connections don't get versions). These versions should also be written to the database. If activities/operators without version are encountered, that will not trigger an error, but the engine will assume they are at version 1. 

Then we need to specify how to upgrade. As part of metadata, each activity or operator can have an upgradeFunctions Object, which looks like (proposal):
const upgradeFunctions = { '2': (formData) => newFormData, '3': (formData) => newFormData)} etc

The idea is that if the engine comes over an activity/operator with a version number lower than the version number of the current activity/operator (because you are importing an old graph, or because you upgraded the activity type, with old data in the database), it will run the migration functions in sequence (if current version is 3, and data is 1, it will run the function at 2, and then the function at 3. If current version is 2, then it will only run the function at 3). 

There should be a similar file for the whole graph (like imports/ui/GraphEditor/upgradeFunctions.js). 

These functions should be given formData, and the output will be the new formData. (Or given whole graph export, and output is new graph export). The main use of the graph upgradeFunctions is renames (if we rename ac-image to ac-gallery), but it could also be used if we changed the structure of all activities in the future.

Then we'll need to make sure that we test for versions when we import (file/server), and when we load a graph in the graph editor/session. 

And of course we need tests.

**Comment by romainAA** [comment]
@houshuang 

So, just to make sure, we need to keep :
- the current version number for each activity and each operator. In their 'meta' along with name,shortDesc… or as a field of the global object along with 'id', config, meta,… ?
- the current version number for graph structure (where ?).
- the upgradeFunctions object for each act/op (as a field of the global object along with 'id', config, meta, mergeFunction… ?)
- the upgradeFunctions for graph structure (as a file of GraphEditor/utils or as part of frog/imports/api/graphs.js?)
- include the version # when addGraph from frog/imports/api/graphs.js is called
- include version # when addActivity from frog/imports/api/activities.js-operators.js is called 
- include version # when we send a graph/act to the remote library
- automatize the version check when a graph is imported from computer or from the remote library or an act from the remote library
Anything else ?

Also, for the upgradeFunctions, from when should we implement them ? 
Because I might be able to find some old data like on the git repo for graphs, but clearly not for all kind of version of all activities and graph since frog started.
Or should we just consider the actual as version number 2 and I try to find 1 previous version for each act/op/graph so that we can just make sure the upgrading engine works ?

**Comment by houshuang** [comment]
1. sure let's make it global
2. I suggest exporting a constant from GraphEditor/versionUpgrades.js called GraphCurrentVersion = 1
3. yeah. let's make it global (not in meta). at some point we should revise the entire structure of ActivityPackages etc, why is something in meta and something not etc, but it's easy to move later
4. maybe api/graphs is cleaner, then you can export currentversion from there too

Let's make current version 1, and forget about anything historical, it's too much work.
