### ISSUE TITLE
[RFC] Export full dashboard packages from frog-utils

### ISSUE THREAD

**Issue by lfaucon** [chili-epfl/FROG#790]
We want to be able to reuse a type of dashboard for several activity types. Right now we export from frog-utils a few chart components, but that is only half of the code required for dashboards.

I suggest exporting from FROG utils full dashboard packages to be reused by activities.

For example in `frog-utils/dashboards/Progress.js`

```
const Viewer = (props) => <div>Hello</div>

const initialData = {}

const mergeLog = (data, dataFn, log) => {
  ...doSomething...
}

export default { Viewer, initialData, mergeLog }
```

And in `ac/ac-quiz/Dashboard.js`

```
import { Progress } from 'frog-utils'

const Viewer = (props) => 
  <div>
    <Progress.Viewer {...props} />
    ...more...
  </div>

const initialData = { ...Progress.intialData, ...more... }

const mergeLog = (data, dataFn, log) => {
  Progress.mergeLog(data, dataFn, log)
  ...more...
}

export { Viewer, initialData, mergeLog }
```

**Comment by houshuang** [comment]
This seems OK for now. We can also switch on the log type in mergeLog, if there are external dashboards that only require certain kinds of log messages.

Going forwards I want to think more about this - enable several dashboards (in a mosaic layout, or a menu - where the layout is not defined by the dashboard package), think about how we can automatically do mergeLog and rendering of certain kinds of data, with more options of drilling down/facetting etc. But since this seems to require minimal core code change, it's a cheap way of experimenting.
