### ISSUE TITLE
ac-quiz display of Latex now broken

### ISSUE THREAD

**Issue by houshuang** [chili-epfl/FROG#802]
See here how it should be: frog.zapto.org/preview/ac-quiz?login=teacher&token=secret

Questions 4 and 5

**Comment by prastut** [comment]
Filing for future use: 

* So the Katex bug seems to originate after the commit https://github.com/chili-epfl/FROG/commit/2f571b17dfec077968c458923bbc382ee71da4d3 as in before https://github.com/chili-epfl/FROG/commit/2f571b17dfec077968c458923bbc382ee71da4d3 there is no problem. The first commit that shows this problem is https://github.com/chili-epfl/FROG/commit/04d5c09bab1e8edff6f570b108c7bcc54e5e046a (which is one commit above https://github.com/chili-epfl/FROG/commit/2f571b17dfec077968c458923bbc382ee71da4d3) and all the commits afterwards.  Checked the commits and I see no change with the katex files. 

* There are some issues that are posted on Katex repo which are somewhat similar to our bug: https://github.com/Khan/KaTeX/issues/45. Read through the answers that maintainers and users have tried and I think we have all the solutions already incorporated into our codebase. 
 * https://github.com/Khan/KaTeX/issues/978
