### ISSUE TITLE
Progress bar in Stroop

### ISSUE THREAD

**Issue by houshuang** [chili-epfl/FROG#909]
Broken after MUI. Probably broken in other activities too (timed quiz). We should have a single way of doing this in frog-utils that is exported, I guess.

![screen shot 2018-03-29 at 12 47 19](https://user-images.githubusercontent.com/61575/38085078-7d2e351c-334f-11e8-9e8e-bd97c763de67.png)

**Comment by prastut** [comment]
@houshuang @lfaucon wanted to discuss whether showing percentage is useful for the students or not. "okay I have done 20% of the task, 80% to go" is a feeling that can be good but often bad in that context (like there is so much left/or so much to do). For quick fast activities, it's mostly good, but I am thinking about activities where progress takes days/months

That's why most progress bars now drop the concept of percentage, they rather compute the width of the progress bar relative to the viewport size. 

There are good blog posts though I tend to disagree with some points as they don't map out completely to our platform's environment: 
* http://babich.biz/progress-indicators/
* http://datagenetics.com/blog/february12017/index.html
 
I hacked a prototype that merge best of both worlds but I still would support dropping percentage completely: 

https://codesandbox.io/s/nn8rrjkk30

**Comment by prastut** [comment]
Discussion moved to #940
