### ISSUE TITLE
RFC mergeLogs 2.0

### ISSUE THREAD

**Issue by houshuang** [chili-epfl/FROG#945]
Currently, the mergeLogs function is called once per log message, and has access to a reactive data collection which is synced with the teacher view, and used to render the dashboard. This can lead to thousands of updates being sent to the teacher's computer when doing very granular logging, which is wasteful and potentially causes disconnects, etc.

# New approach:
mergeData gets access to a persistent state, called localState (using inMemory, not ShareDB) which is not synced anywhere. 

## Given this, there are three possible approaches:
- the whole localState is synced to the teacher's client, the only difference is that this only happens for example once per second, reducing by a factor of 10 the number of updates sent, but not changing anything else. This would require the fewest changes to the existing activities.
- given that we might sometimes want to keep much more data in state than is actually displayed (for example ac-quiz, where we might want to keep each person's full answers, but what we display is just an aggregated number of answers per question alternative), the mergeData function also has access to a syncedState object, which is updated on each log merge, but only synced to the client for example once per second
- OR the mergeData function only updates the localState object, and then there is a second function, generateRenderData, which is run once per second, and which gets the localData as input, and whose output are sent to the teacher. (in the future we could also have a system of subscriptions, so that this function is only run, and the data for a dashboard only synced to the client, while a teacher is actually looking at a given dashboard).

The idea would be to move a lot of [this code](https://github.com/chili-epfl/FROG/blob/develop/frog-utils/src/dashboards/progress.js#L57-L84) into the generateRenderData on the server.

## Technical considerations
For this to work, it's crucial that all log messages are processed in a single Meteor process, and single-threaded (ie. that it's not trying to process two log messages at exactly the same time). I think the second thing should not be a problem, but I will check to make sure.

In development mode, this will be easy. For production, I will designate one process the log processor, which will be listening to the Redis stream that we have set up anyway and take all incoming log messages. The other servers will take the incoming log messages, write them to the Mongo, and put them on the Redis queue to be processed. This will of course have to be tested thoroughly.

Also, if FROG restarts in the middle of a session, it will load the log messages from Mongo and recreate the localState (similar to how the dashboard preview works right now). This means that mergeData should be a pure function (ie. give the same output no matter when it's run, given the same input).

**Comment by lfaucon** [comment]
I like the idea of the generateRenderData. For many dashboards this code either lives in the mergeLog data, but sometime lives in the dashboard viewer render function, which is obviously less efficient.

What do you think of computing the dashboard data only when the teacher requires it through a procedure call? That means on the server querying the logs since the local state computed, and computing the new local state. That query could be sent every second by the teacher if he has the dashboard or teacherView open. This seems to be an easy solution for having only one meteor server doing the work without needing a special process or differences between dev/prod.

Also, if we are not using sharedb anymore, I don't see the point of using inMemorySharedb or pureObjectShardb. These are slower than manipulating normal javascript objects. We could have `mergeLog(localState: Object, metaData: Object, logs: Object[]) => newLocalState: Object`. Instead of doing these sharedb side effects which are less intuitive for developer (If you look for example at the first version of the mergeLog for the progress dashboard that Jenny wrote).
